# Generated by Django 2.2.5 on 2019-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('transaction_id', models.BigIntegerField()),
                ('summary', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]