# Generated by Django 2.2.5 on 2019-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('transaction_id', models.BigIntegerField()),
                ('summary', models.TextField()),
                ('wallet', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('stock_symbol', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        )
    ]
